BROADCASTING & VECTORIZATION

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])
result = []
for i in arr:
    result.append(i**2)
print(result)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [4]:
#Another Method for same 
arr = np.array([1,2,3,4,5])
result = arr ** 2
print(result)

[ 1  4  9 16 25]


In [5]:
arr = np.array([1,2,3,4,5])
result = arr + 10
print(result)

[11 12 13 14 15]


In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])
result = arr1 + arr2
print(result)

[[2 4 6]
 [5 7 9]]


In [9]:
#Normalizing Data using Braodcasting
data = np.array([[10,20,30],[15,25,35],[20,30,40],[25,35,45],[30,40,50]])
mean = data.mean(axis = 0)
std = data.std(axis = 0)
result = (data - mean) // std
print(result)

[[-2. -2. -2.]
 [-1. -1. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
