Creating Numpy Arrays And Using Some Of There Methods 

In [3]:
#Creating an array in numpy 
import numpy as np
arr = np.array([1,3,4])
arr

array([1, 3, 4])

In [4]:
#creating or generating mutiple dimensional array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
np.ones((1,2))

array([[1., 1.]])

In [8]:
np.full((2,2),8)

array([[8, 8],
       [8, 8]])

In [9]:
#generating identity matrix of any dimensional
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [11]:
#generating a particular range
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [12]:
np.arange(1,100,20)

array([ 1, 21, 41, 61, 81])

In [17]:
np.arange(1,100,19)

array([ 1, 20, 39, 58, 77, 96])

In [24]:
#generating evenly spaced value of array
arr = np.linspace(0,100,5)
arr

array([  0.,  25.,  50.,  75., 100.])

In [23]:
arr.astype("float64")
arr

array([1, 3, 4])

In [21]:
arr.astype("int64")

array([1, 3, 4])

In [22]:
arr

array([1, 3, 4])

In [29]:
arr = np.linspace(0,100,5,dtype = np.int64)
arr

array([  0,  25,  50,  75, 100])

In [31]:
#checking the properties of array
arr = np.array([[10,20,30],[40,50,60]])
print("Shape is : ",arr.shape)
print("Size : ",arr.size)
print("Dimensional : ",arr.ndim)
print("Data types : ",arr.dtype)

Shape is :  (2, 3)
Size :  6
Dimensional :  2
Data types :  int64


In [32]:
#changing the data type 
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]],dtype = 'float32')
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [33]:
myarr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]],dtype = 'int64')
myarr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [34]:
n = myarr.astype("float64")
n.dtype

dtype('float64')

In [39]:
#Reshaping the array
print(myarr)
myarr.shape

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [11. 12. 13.]]


(4, 3)

In [37]:
reshaped = myarr.reshape((3,4))

In [38]:
reshaped

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 11., 12., 13.]], dtype=float32)

In [40]:
#Converting the 2D array to 1D
flattened = myarr.flatten()
print(flattened)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 11. 12. 13.]


In [41]:
flattened = myarr1.flatten()
print(flattened)

[ 1  2  3  4  5  6  7  8  9 11 12 13]
