Indexing And Slicing in Numpy Array

In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
#flatting the array
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
flat[0]

np.int64(1)

In [5]:
flat[3:6]

array([4, 5, 6])

In [6]:
flat[:5]

array([1, 2, 3, 4, 5])

In [23]:
#Slicing the numpy array without using the .copy() method
flat = arr.flatten()
b = flat[3:7]
b[0] = 4444
print(b)
print(flat) #Without using .copy() method the changes maded in the slice view it will also reflect in main array

[4444    5    6    7]
[   1    2    3 4444    5    6    7    8    9   10   11   12]


In [24]:
#Slicing the numpy array with th euse of .copy() method
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
flat = arr2.flatten()
b = flat[3:7].copy()
b[0] = 4444
print(b)
print(flat) # here the changes maded are only reflected in the copy of the main array

[4444    5    6    7]
[1 2 3 4 5 6 7 8 9]


In [29]:
#fancy indexing and boolean masking
# selecting the multiple elements 
arr = flat
print(arr)
print(arr[[3,6,8]])

[1 2 3 4 5 6 7 8 9]
[4 7 9]


In [32]:
#boolean masking
arr[arr>6]

array([7, 8, 9])