Multidimensional Indexing and Axis in Numpy

In [2]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0] #accessing the rows in numpy array

array([1, 2, 3])

In [5]:
 np.sum(arr,axis = 0) #It will give sum of all rows in numpy 

array([12, 15, 18])

In [6]:
np.sum(arr,axis = 1) # It will give the sum of all columns in numpy array

array([ 6, 15, 24])

In [11]:
# Indexing in multidimensional array
print(arr[0][1])
arr[0:2,1:3] 

2


array([[2, 3],
       [5, 6]])

In [18]:
arr3d = np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])
print(arr3d)
print("Its Shape is : ",arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Its Shape is :  (2, 2, 3)


In [19]:
#Accessing the elements in 3d
print(arr3d[0,1,2])

6


In [20]:
print(arr3d[:,0,:])

[[1 2 3]
 [7 8 9]]


In [22]:
#Selecting the data along with axes
first_col = arr[:,0]
print(first_col) # it will give all rows of first columns

[1 4 7]


In [23]:
#it will give all the first row in all 2d arrays 
first_row = arr3d[:,0,:]
print(first_row)

[[1 2 3]
 [7 8 9]]


In [24]:
#Changing Data along with axis
arr[:,1] = 0 # It will replace all elements in column 1 with 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
