Exercise for Numpy Array

1. Create a 3x3 array filled with random numbers and print the shape

In [10]:
import numpy as np

arr1 = np.random.randint(2,10,(3,3))
print(arr1)
print(arr1.shape)

[[5 7 3]
 [7 7 3]
 [9 2 6]]
(3, 3)


2. Convert an array of floats [1.1,2.2,3.3] into int

In [11]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype = "float64")
arr2

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [12]:
changed_data = arr2.astype("int64")
changed_data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

3. Use Fancy Indexing To Extract Even Numbers From [1,2,3,4,5,6,7,8,9,10]

In [25]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
arr3
even_no = arr3[arr3%2 == 0]
print(even_no)

[ 2  4  6  8 10]


4. Reshape a 1D array of size a into a 3x3 matrix

In [26]:
arr4 = np.array([1,2,3,4,5,6,7,8,9])
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
reshaped = arr4.reshape((3,3))
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5. Use the Boolean Making a filter number for greater then 50 in an array

In [38]:
arr5 = np.random.randint(30,90,(5,6))
arr5

array([[57, 44, 31, 46, 38, 67],
       [89, 48, 46, 73, 70, 46],
       [61, 86, 79, 83, 77, 80],
       [44, 39, 31, 46, 40, 81],
       [64, 36, 71, 50, 76, 62]], dtype=int32)

In [39]:
arr5[arr5 > 50]

array([57, 67, 89, 73, 70, 61, 86, 79, 83, 77, 80, 81, 64, 71, 76, 62],
      dtype=int32)